config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  resources :events do
    resources :rounds do
      resources :games
        resources :teams
      resources :players
    end
    resources :players
  end

  root 'events#index'
end

app/models/rank_history.rb
class RankHistory < ApplicationRecord
  belongs_to :player
  belongs_to :game
end

app/models/team.rb
class Team < ApplicationRecord
    belongs_to :event
    has_and_belongs_to_many :players
    has_one :game
end

app/controllers/rank_history_controller.rb
class RankHistoryController < ApplicationController
    before_action :get_event
    before_action :get_player

    def new
        @rankhistory = RankHistory.new
    end

    def create
        @rankhistory = RankHistory.new(rankhistory_params)

        if @rankhistory.save
            redirect_to @rankhistory
        else
            render 'new'
        end
    end

    def show
        @rankhistory = RankHistory.find(params[:id])
    end

    def index
        @rankhistorys = RankHistory.all
    end

    def edit
        @rankhistory = RankHistory.find(params[:id])
    end

    def update
        @rankhistory = RankHistory.find(params[:id])

        if @rankhistory.update(rankhistory_params)
            redirect_to event_player_path(@event,@player)
        else
            render 'edit'
        end
    end

    private
        def rankhistory_params
            params.require(:rankhistory).permit(:event_id, :player_id)
        end

        def get_event
            @event = Event.find(params[:event_id])
        end

        def get_player
            @player = Event.find(params[:player_id])
        end
end

app/helpers/rank_history_helper.rb
module RankHistoryHelper
end

app/views/rank_history/_form.html.erb
<%= form_with model: @round, url: [@event, @round], :html => { :onsubmit => 'return validateRoundForm();' }, local: true do |form| %>

    <p id="jserrors"></p>
    <% if @round.errors.any? %>
        <div id="error_explanation">
            <h2>
                <%= pluralize(@round.errors.count, "error") %> prohibited
                this round from being saved:
            </h2>
            <ul>
                <% @round.errors.full_messages.each do |msg| %>
                    <li><%= msg %></li>
                <% end %>
            </ul>
        </div>
    <% end %>
    <p>
        <%= form.label :name %><br>
        <%= form.text_field :name %>
    </p>

    <p>
        <%= form.label :datetime %><br>
        <%= form.datetime_select :datetime %>
    </p>

    <p>
        <%= form.label :Number_of_games %><br>
        <%= form.number_field :numgames %>
    </p>
    
    <p>
        <%= form.check_box :started%> <%= form.label :started %>
    </p>

    <h2>Players</h2>
<table>
  <tr>
    <th>Attending</th>
    <th>Name</th>
  </tr>
 
  <% @event.players.order("name asc").each do |player| %>
    <tr>
      <td><%= check_box_tag :player_ids, player.id, form.object.players.include?(player), :name => 'round[player_ids][]' %>
      <td><%= player.name %></td>
    </tr>
  <% end %>
</table>

    <p>
        <%= form.submit %>
    </p>
<% end %>

app/views/rank_history/edit.html.erb
<h1>Edit Round</h1>

<%= render 'form' %>

<%= link_to 'Back', event_path(@event) %>

app/views/rank_history/index.html.erb
<h1>Rounds</h1>
 
<table>
  <tr>
    <th>Name</th>
    <th>Date</th>
    <th>Actions</th>
  </tr>
 
  <% @rounds.each do |round| %>
    <tr>
      <td><%= event.name %></td>
      <td><%= link_to 'Show', event_round_path(@event, round) %></td>
      <td><%= link_to 'Edit', edit_event_path(@event, round) %></td>
    </tr>
  <% end %>
</table>

<p>
    <%= link_to 'New Event', new_event_round_path(@event) %>
</p>

app/views/rank_history/new.html.erb
<h1>New Round</h1>

<%= render 'form' %>

<%= link_to 'Back', events_path %>

app/views/rank_history/show.html.erb
<p>
  <strong>Name:</strong>
  <%= @rankhistory.player.name %>
</p>
 
<p>
  <strong>Datetime:</strong>
  <%= @round.datetime %>
</p>

<% if @round.started %>
  <h2>Games</h2>
  <% if @round.games.present? %>
  <% @round.games.each do |game| %>
  <table>
    <tr>
      <td>
        <strong>Game</strong> <%= link_to 'Edit', edit_event_round_game_path(@event, @round,game) %><br>
        <%= check_box("complete", game.complete, {checked: game.complete, disabled: true}) %> complete
      </td>
    </tr>
    <tr>
      <td><%= link_to 'Home', event_round_team_path(@event,@round,game.team1) %> - <%= game.t1score %></td>
      <td><%= link_to 'Visitor', event_round_team_path(@event,@round,game.team2) %> - <%= game.t2score %></td>
    </tr>
    <tr>
      <td>
        <table>
          <% game.team1.players.each do |player| %>
          <tr>
            <td><%= player.name %></td>
            <td><%= player.tskill.round(5)%></td>
            <td><%= player.points%></td>
          </tr>
          <% end %>
        </table>
      </td>
      <td>
        <table>
          <% game.team2.players.each do |player|%>
          <tr>
            <td><%= player.name %></td>
            <td><%= player.tskill.round(5)%></td>
            <td><%= player.points%></td>
          </tr>
          <% end %>
        </table>
      </td>
     </tr>
    <% end %>
    <% end %>
  </table>
  <br>
<% end %>

<% unless @round.started %>
<div id="players_div">
<h2>Players</h2>
<table>
  <tr>
    <th>Attending</th>
    <th>Name</th>
  </tr>
 
  <% @event.players.order("name asc").each do |player| %>
    <tr>
      <td><%= check_box_tag :player_ids, player.id, @round.players.include?(player), :name => 'round[player_ids][]', :disabled => true %>
      <td><%= player.name %></td>
    </tr>
  <% end %>
</table>
</div>
<% end %>

<%= link_to 'Back', event_path(@event) %>