config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  resources :events do
    resources :rounds do
      resources :games
        resources :teams
      resources :players
    end
    resources :players
  end

  root 'events#index'
end

app/models/event.rb
class Event < ApplicationRecord
    has_many :rounds
    has_many :players
    has_many :teams
    has_many :games, :through => :rounds

    validates :name, presence: true
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
    def new
        @event = Event.new
    end

    def create
        @event = Event.new(event_params)

        if @event.save
            redirect_to @event
        else
            render 'new'
        end
    end

    def show
        @event = Event.find(params[:id])
    end

    def index
        @events = Event.all
    end

    def edit
        @event = Event.find(params[:id])
    end

    def update
        @event = Event.find(params[:id])

        if @event.update(event_params)
            redirect_to @event
        else
            render 'edit'
        end
    end

    private
        def event_params
            params.require(:event).permit(:name, :description, :teamsize, :points_for_win, :points_for_loss)
        end
end

app/helpers/events_helper.rb
module EventsHelper
end

app/views/events/_form.html.erb
<%= form_with model: @event, local: true do |form| %>

    <% if @event.errors.any? %>
        <div id="error_explanation">
            <h2>
                <%= pluralize(@event.errors.count, "error") %> prohibited
                this event from being saved:
            </h2>
            <ul>
                <% @event.errors.full_messages.each do |msg| %>
                    <li><%= msg %></li>
                <% end %>
            </ul>
        </div>
    <% end %>
    <p>
        <%= form.label :name %><br>
        <%= form.text_field :name %>
    </p>

    <p>
        <%= form.label :description %><br>
        <%= form.text_area :description %>
    </p>

    <p>
        <%= form.label :teamsize %><br>
        <%= form.number_field :teamsize %>
    </p>

    <p>
        <%= form.label :points_for_win %><br>
        <%= form.number_field :points_for_win %>
    </p>

    <p>
        <%= form.label :points_for_loss %><br>
        <%= form.number_field :points_for_loss %>
    </p>

    <p>
        <%= form.submit %>
    </p>
<% end %>

app/views/events/edit.html.erb
<h1>Edit Event</h1>

<%= render 'form' %>

<%= link_to 'Back', events_path %>

app/views/events/index.html.erb
<h1>Events</h1>
 
<table>
  <tr>
    <th>Name</th>
    <th>Actions</th>
  </tr>
 
  <% @events.each do |event| %>
    <tr>
      <td><%= event.name %></td>
      <td><%= link_to 'Show', event_path(event) %></td>
      <td><%= link_to 'Edit', edit_event_path(event) %></td>
    </tr>
  <% end %>
</table>

<p>
    <%= link_to 'New Event', new_event_path %>
</p>

app/views/events/new.html.erb
<h1>New Event</h1>

<%= render 'form' %>

<%= link_to 'Back', events_path %>

app/views/events/show.html.erb
<p>
  <strong>Name:</strong>
  <%= @event.name %>
</p>
 
<p>
  <strong>Description:</strong>
  <%= @event.description %>
</p>

<h2>Rounds</h2>
<table>
  <tr>
    <th>Name</th>
    <th>Datetime</th>
  </tr>
 
  <% @event.rounds.order("datetime desc").each do |round| %>
    <tr>
      <td><%= round.name %></td>
      <td><%= round.datetime %></td>
      <td><%= link_to 'Show', event_round_path(@event, round) %></td>
      <td><%= link_to 'Edit', edit_event_round_path(@event, round) %></td>
    </tr>
  <% end %>
</table>    

<%= link_to 'Add Round', new_event_round_path(@event) %>

<h2>Players</h2>
<table>
  <tr>
    <th>Name</th>
    <th>TrueSkill</th>
    <th>TrueSkill Deviation</th>
    <th>Points</th>
    <th>Actions</th>
  </tr>
 
  <% @event.players.order("tskill desc").each do |player| %>
    <tr>
      <td><%= player.name %></td>
      <td><%= player.tskill.round(5) %></td>
      <td><%= player.tdeviation.round(5) %></td>
      <td><%= player.points %></td>
      <td><%= link_to 'Show', event_player_path(@event, player) %></td>
      <td><%= link_to 'Edit', edit_event_player_path(@event, player) %></td>
    </tr>
  <% end %>
</table>    

<%= link_to 'Add Player', new_event_player_path(@event) %>

<%= link_to 'Back', events_path %>