config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  resources :events do
    resources :rounds do
      resources :games
        resources :teams
      resources :players
    end
    resources :players
  end

  root 'events#index'
end

app/models/game.rb
class Game < ApplicationRecord
  belongs_to :team1, :class_name => "Team"
  belongs_to :team2, :class_name => "Team"
  belongs_to :round
  has_many :rank_history

  validate :complete_with_scores

  private
    def complete_with_scores
      if complete && (t1score == t2score)
        errors.add(:t1score, "cannot be equal to T2score")
      end
    end
end

app/controllers/games_controller.rb
class GamesController < ApplicationController
    include Saulabs::TrueSkill

    before_action :get_round
    before_action :get_event_from_round
    def new
        @game = Game.new
    end

    def create
        @game = Game.new(game_params)
        @game.event = @event
        if @game.save
            redirect_to event_round_game_path(@round,@game)
        else
            render 'new'
        end
    end

    def show
        @game = Game.find(params[:id])
    end

    def index
        @games = Game.all
    end

    def edit
        @game = Game.find(params[:id])
    end

    def update
        @game = Game.find(params[:id])

        old_complete = @game.complete

        if @game.update(game_params)
            if @game.complete && !old_complete
                update_ratings()
            end
            redirect_to event_round_path(@event,@round)
        else
            render 'edit'
        end
    end

    private
        def update_ratings
            team1t = []
            team2t = []
            team1activity = (@game.team1.players.length.to_f/@event.teamsize)
            @game.team1.players.each do |player|
                pt = Saulabs::TrueSkill::Rating.new(player.tskill,player.tdeviation,team1activity)
                team1t << pt
            end
            team2activity = (@game.team2.players.length.to_f/@event.teamsize)
            @game.team2.players.each do |player|
                pt = Saulabs::TrueSkill::Rating.new(player.tskill,player.tdeviation,team2activity)
                team2t << pt
            end

            tgraph = nil
            if @game.t1score > @game.t2score
                puts "Starting t update: " + Time.now.strftime("%d/%m/%Y %H:%M:%S")
                tgraph = Saulabs::TrueSkill::FactorGraph.new({team1t => 1, team2t => 2},{:draw_probability => 0.0, :skills_additive => false})
                tgraph.update_skills
                puts "Ending t update: " + Time.now.strftime("%d/%m/%Y %H:%M:%S")

                add_player_ratings_and_points(team:@game.team1, points:@event.points_for_win, tratings: tgraph.teams[0])
                add_player_ratings_and_points(team:@game.team2, points:@event.points_for_loss, tratings: tgraph.teams[1])
            else
                tgraph = Saulabs::TrueSkill::FactorGraph.new({team2t => 1, team1t => 2},{:draw_probability => 0.0, :skills_additive => false})
                tgraph.update_skills
                
                add_player_ratings_and_points(team:@game.team2, points:@event.points_for_win, tratings: tgraph.teams[0])
                add_player_ratings_and_points(team:@game.team1, points:@event.points_for_loss, tratings: tgraph.teams[1])
            end
        end

        def add_player_ratings_and_points(team:, points:, tratings: [])
            x = 0
            team.players.each do |player|
                player.points = player.points + points
                player.tdeviation = tratings[x].deviation
                player.tskill = tratings[x].mean
                player.save
                rh = RankHistory.new()
                rh.player = player
                rh.game = @game
                rh.tskill = player.tskill
                rh.tdeviation = player.tdeviation
                rh.points = player.points
                rh.save
                x = x + 1
            end
        end

        def game_params
            params.require(:game).permit(:round_id, :complete, :t1score, :t2score)
        end

        def get_round
            @round = Round.find(params[:round_id])
        end
        def get_event_from_round
            if params[:event_id].present?
                @event = Event.find(params[:event_id])
            else
                @event = @round.event
            end
        end
end

app/helpers/games_helper.rb
module GamesHelper
end

app/views/games/_form.html.erb
<%= form_with model: @game, url: [@event, @round, @game], local: true do |form| %>

    <p id="jserrors"></p>
    <% if @game.errors.any? %>
        <div id="error_explanation">
            <h2>
                <%= pluralize(@game.errors.count, "error") %> prohibited
                this round from being saved:
            </h2>
            <ul>
                <% @game.errors.full_messages.each do |msg| %>
                    <li><%= msg %></li>
                <% end %>
            </ul>
        </div>
    <% end %>
    
    <p>
        <%= form.check_box :complete%> <%= form.label :complete %>
    </p>

    <table>
        <tr>
          <td>Home<br><%= form.label :score %> <%= form.number_field :t1score %></td>
          <td>Visitor<br><%= form.label :score %> <%= form.number_field :t2score %></td>
        </tr>
        <tr>
          <td>
            <table>
              <% @game.team1.players.each do |player| %>
              <tr>
                <td><%= player.name %></td>
              </tr>
              <% end %>
            </table>
          </td>
          <td>
            <table>
              <% @game.team2.players.each do |player|%>
              <tr>
                <td><%= player.name %></td>
              </tr>
              <% end %>
            </table>
          </td>
         </tr>
    </table>

    <p>
        <%= form.submit %>
    </p>
<% end %>

app/views/games/edit.html.erb
<h1>Edit Game</h1>

<%= render 'form' %>

<%= link_to 'Back', event_round_path(@event,@round) %>

app/views/games/index.html.erb
<h1>Games</h1>
 
<table>
  <tr>
    <th>Name</th>
    <th>Date</th>
    <th>Actions</th>
  </tr>
 
  <% @games.each do |game| %>
    <tr>
      <td><%= game.id %></td>
      <td><%= link_to 'Show', event_event_round_game_path(@round,@game) %></td>
      <td><%= link_to 'Edit', edit_event_round_game_path(@round, @game) %></td>
    </tr>
  <% end %>
</table>

<p>
    <%= link_to 'New Event', new_event_round_game_path(@round,@game) %>
</p>

app/views/games/new.html.erb
<h1>New Game</h1>

<%= render 'form' %>

<%= link_to 'Back', events_path %>

app/views/games/show.html.erb
<p>
  <%= check_box("complete", @game.complete ,{checked: @game.complete, disabled: true}) %> complete
</p>

<table>
  <tr>
    <td><%= link_to 'Home', event_round_team_path(@event,@round,@game.team1) %> - <%= @game.t1score %></td>
    <td><%= link_to 'Visitor', event_round_team_path(@event,@round,@game.team2) %> - <%= @game.t2score %></td>
  </tr>
  <tr>
    <td>
      <table>
        <% @game.team1.players.each do |player| %>
         <tr>
          <td><%= player.name %></td>
         </tr>
         <% end %>
      </table>
    </td>
    <td>
      <table>
        <% @game.team2.players.each do |player|%>
        <tr>
          <td><%= player.name %></td>
        </tr>
        <% end %>
      </table>
    </td>
  </tr>
</table>

<%= link_to 'Back', event_round_path(@event,@round) %>